services:

  customer-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_DATABASE: review-db

  customer-service:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - review-db